version: "{build}"

clone_folder: c:\gopath\src\github.com\gen2brain\raylib-go

environment:
  GOPATH: c:\gopath
  MSYS_PATH: c:\msys64
  CGO_ENABLED: 1
  CGO_CFLAGS: -Ic:\msys64\mingw64\include

install:
  - echo %GOPATH%
  - echo %MSYS_PATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%MSYS_PATH%\usr\bin;%PATH%
  - go version
  - go env

before_build:
  - bash -lc "pacman --noconfirm --needed -Sy mingw-w64-x86_64-openal"

build_script:
  - bash -lc "cd /c/gopath/src/github.com/gen2brain/raylib-go && make"
