language: go

go:
  - 1.7.x
  - tip

install:
  - sudo apt-get install libopenal-dev libxi-dev libxinerama-dev libxcursor-dev libxxf86vm-dev -y

  - curl -s -L wget http://www.cmake.org/files/v3.7/cmake-3.7.2.tar.gz | tar xz
  - cd cmake-3.7.2
  - ./configure
  - make
  - sudo make install
  - cd ..

  - curl -s -L https://github.com/glfw/glfw/archive/3.2.1.tar.gz | tar -xz
  - cd glfw-3.2.1
  - mkdir -p build && cd build && cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr ..
  - make
  - sudo make install
  - cd ../..
